# Generated by Django 5.2.5 on 2025-09-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="category",
            field=models.TextField(),
        ),
    ]
