# Generated by Django 5.2.5 on 2025-09-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_observation_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="RbiNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("link", models.URLField(unique=True)),
                (
                    "published_at",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_role",
            field=models.CharField(
                choices=[
                    ("Branch Manager", "Branch Manager"),
                    ("HO Manager", "HO Manager"),
                    ("HO Audit", "HO Audit"),
                    ("Admin", "Admin"),
                ],
                default="Branch Manager",
                max_length=50,
            ),
        ),
    ]
